# This workflow creates a release pull request whenever a change is pushed to 'main'.
# When the release pull request is merged into 'main', it will automatically create and tag a new
# release version.

name: Release automation
on:
  push:
    branches:
      - "main"
      - "hotfix/*"
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    name: Create a new release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          target-branch: ${{ github.ref_name }}